version: '3.7'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost
    volumes:
      - db-volume:/var/lib/postgresql/data

  app:
    image: mattermost/mattermost-team-edition:latest
    restart: always
    ports:
      - "8065:8065"
    environment:
      MM_CONFIG: /mattermost/config/config.json
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mattermost
      DB_USER: mmuser
      DB_PASSWORD: mmuser_password
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10"
    depends_on:
      - db
    volumes:
      - app-volume:/mattermost/data

volumes:
  db-volume:
  app-volume: 